const ts=require('typescript');const fs=require('fs');const {DatabaseSync}=require('node:sqlite');const assert=require('node:assert/strict');
const root=require('path').resolve(__dirname,'..');const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync(root+'/drizzle').filter(x=>x.endsWith('.sql')).sort())sql.exec(fs.readFileSync(root+'/drizzle/'+f,'utf8'));
let user=null;const adapter={prepare(q){return {args:[],bind(...a){this.args=a;return this},async first(){return sql.prepare(q).get(...this.args)||null},async all(){return {results:sql.prepare(q).all(...this.args)}},async run(){const r=sql.prepare(q).run(...this.args);return {meta:{changes:r.changes}}}}},async batch(stmts){sql.exec('BEGIN');try{const r=await Promise.all(stmts.map(s=>s.run()));sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
let helper=fs.readFileSync(root+'/lib/programa.ts','utf8').replace(/import .*?;\n/,'').replace(/export function db\(\).*?\n/,'').replace(/export function ownerEmail\(\).*?\n/,'').replaceAll('export ','');
let route=fs.readFileSync(root+'/app/api/programa/route.ts','utf8').replace(/^import .*;\n/gm,'').replaceAll('export ','');
const js=ts.transpile(helper+'\n'+route,{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS});const handlers=new Function('db','ownerEmail','getChatGPTUser',js+';return {GET,POST}')( ()=>adapter,()=> 'admin@example.test',async()=>user);
let checks=0;async function call(body,id=null){user=id?{userId:id,email:id+'@example.test'}:null;const r=await handlers.POST(new Request('https://athos.test/api/programa',{method:'POST',headers:{origin:'https://athos.test','content-type':'application/json'},body:JSON.stringify(body)}));return {status:r.status,data:await r.json()}}
async function read(id){user=id?{userId:id,email:id+'@example.test'}:null;return (await handlers.GET(new Request('https://athos.test/api/programa'))).json()}
function ok(v){assert.ok(v);checks++}
(async()=>{const base={action:'register',name:'Administrador teste',cpf:'52998224725',phone:'62999999999',email:'admin@example.test',consent:true,adminSetup:true};ok((await call(base,'admin')).status===200);ok((await call({...base,cpf:'11144477735'},'intruder')).status!==200);const a=await read('admin');const reg=await call({...base,adminSetup:false,code:a.person.code,name:'Participante teste',cpf:'11144477735',email:'member@example.test'},'member');ok(reg.status===200);const m=await read('member');ok(m.person.parent===a.person.id);const lead={action:'lead',code:m.person.code,parentName:'Responsável teste',parentCpf:'52998224725',phone:'62999999999',childName:'Aluno teste',childCpf:'12345678909',age:8,grade:'3º ano',consent:true};ok((await call(lead)).status===200);ok((await call(lead)).status===409);ok((await call({...lead,childCpf:'11144477735',childName:'Outro filho teste'})).status===409);let ml=await read('member');ok(ml.leads[0].parent_name==='Responsável teste'&&!('child_name' in ml.leads[0]));ok(ml.leads.length===1&&!('parent_cpf' in ml.leads[0])&&!('phone' in ml.leads[0]));const id=ml.leads[0].id;ok((await call({action:'status',id,status:'enrolled'},'member')).status===403);ok((await call({action:'status',id,status:'discount_applied'},'admin')).status===400);ok((await call({action:'tuition',value:580},'admin')).status===200);ok((await call({action:'status',id,status:'enrolled'},'admin')).status===400);ok((await call({action:'status',id,status:'enrolled',referrerTuition:580,discountMonth:'2026-10'},'admin')).status===200);ok((await read('member')).leads[0].reward===29000);ok((await read('member')).leads[0].discount_month==='2026-10');ok((await read('member')).leads[0].benefit_kind==='discount');await call({action:'tuition',value:800},'admin');await call({action:'status',id,status:'enrolled'},'admin');ok((await read('member')).leads[0].reward===29000);ok((await call({action:'status',id,status:'discount_applied'},'admin')).status===200);ok((await call({action:'status',id,status:'cancelled'},'admin')).status===400);ok(!(await read(null)).person);console.log(checks+' verificações passaram: indicação por CPF, permissões, desconto de 50% na mensalidade do indicador, competência e aplicação do desconto.');})().catch(e=>{console.error(e);process.exit(1)});
